### ISSUE TITLE
Can't add second identity

### ISSUE THREAD

**Issue by khssnv** [BTE-Trusted-Entity/sporran-extension#1386]
### How to reproduce

1. Create the first identity in Sporran extension,
2. Use "Add identity" to add one by seed phrase,
3. Click "Import an identity from pre-existing phrase", type your seed phrase and click "Next step",
4. Type a relevant password until all password requirements are fulfilled,
5. Nothing happens when you click "Next step".

### Environment

```console
$ uname -a
Linux e14 5.13.0-40-generic #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ brave-browser --version
Brave Browser 100.1.37.116
```

Extension: Sporran Version 2022.4.14

**Comment by arty-name** [comment]
Thank you for reporting this issue! Given how the Brave browser uses the same engine as Google Chrome we expect it to work the same way and support the Sporran extension. Nevertheless it is not an officially supported platform for Sporran and we do not test in it. If you encounter issues, we recommend to use Sporran in Mozilla Firefox or Google Chrome.
